pipeline {
    agent any

    stages {
        stage('Build NGINX Image') {
            steps {
                sh '''
                  docker build -t custom-nginx:1.0 ./nginx
                '''
            }
        }

        stage('Deploy NGINX') {
            steps {
                sh '''
                  docker rm -f prod-nginx || true
                  docker run -d \
                    --name prod-nginx \
                    -p 80:80 \
                    custom-nginx:1.0
                '''
            }
        }
    }

    post {
        success {
            echo 'NGINX deployed successfully'
        }
        failure {
            echo 'Deployment failed'
        }
    }
}

