FROM jenkins/jenkins:lts

USER root

RUN apt-get update && apt-get install -y docker.io && apt-get clean

ARG DOCKER_GID=1001

RUN groupmod -g ${DOCKER_GID} docker && usermod -aG docker jenkins

USER jenkins
